### ISSUE TITLE
ready event doesn't work on onDocument controllers

### ISSUE THREAD

**Issue by vkornov** [jupiterjs/jquerymx#1]
given following code:

jQuery.Controller.extend('ExampleController',
/\* @Static _/
{
       onDocument: true
},
/_ @Prototype */
{
       ready: function() {
               //not called
       }
});

The ready event handler is not invoked.

**Comment by jefferyto** [comment]
SHA: jeff-themovie@03c4ad97227f761f46b7b4554ac6865536fa7f5c should fix the issue.

**Comment by vkornov** [comment]
fixed?..

**Comment by jefferyto** [comment]
Fixed in SHA: 69aeb25a986a7c9bf1b4822def1565563e124617 (not sure why the document event handler can't be unbound though)

**Comment by vkornov** [comment]
Because it's not a real event?

**Comment by jefferyto** [comment]
That doesn't mean $(document).unbind('ready', ...) won't work.
