### ISSUE TITLE
formParams() can now only be called on <form> element. formParams() called on other than <form> element returns undefined

### ISSUE THREAD

**Issue by arjunballa** [jupiterjs/jquerymx#118]
The new version of formParams() required to be called only on <form> element.

formParams() called on other than <form>  element returns undefined.

// new code
if ( params ) {
   return this.setParams( params );
} else if ( this.is("form") ) {
  return this.getParams( convert );
}

// old code
if ( this[0].nodeName.toLowerCase() == 'form' && this[0].elements ) {
                return jQuery(jQuery.makeArray(this[0].elements)).getParams(convert);
}
return jQuery("input[name], textarea[name], select[name]", this[0]).getParams(convert); // this condition is not covered

**Comment by ralphholzmann** [comment]
Are you saying this is a bug? Would you like it be available on non-form elements? Seems like an easy fix.

**Comment by arjunballa** [comment]
It is working!!
Thanks for quick fix
