### ISSUE TITLE
Cookie: jQuery.evalJSON and jQuery.toJSON

### ISSUE THREAD

**Issue by sethaldridge** [jupiterjs/jquerymx#124]
Hi,

I was looking through the Cookie.js code and found two methods `jQuery.evalJSON` and `jQuery.toJSON`. Looking through the jQuery docs these methods don't exist and I wasn't sure if jQueryMX was adding them or if you meant `jQuery.parseJSON`?

I couldn't find any current information on them so I wanted to verify the usage before creating a pull request around the update.

**Comment by daffl** [comment]
It's part of the jQuery JSON plugin at [jquery/lang/json](https://github.com/jupiterjs/jquerymx/blob/master/lang/json/json.js) which ships with jQueryMX.

**Comment by sethaldridge** [comment]
Perfect. Thanks!
