### ISSUE TITLE
Jquery generates wrong path to common HTML file in functional tests

### ISSUE THREAD

**Issue by dnesteryuk** [jupiterjs/jquerymx#15]
Execute following steps:

./js jquery/generate/app some_test
./js jquery/generate/scaffold SomeTest.Models.Recipe

Then open some_test/test/funcunit/recipe_controller_test.js. Find the line 4

S.open("//some_test/sometest.html");

As you can see the name of common file is wrong. It should be:

S.open("//some_test/some_test.html");

**Comment by jupiterjs** [comment]
thanks ... fixing ...

**Comment by jupiterjs** [comment]
fixed: https://github.com/jupiterjs/steal/commit/ce96c4bb0e570ce95cfe597ff05ca930c5265de6
