### ISSUE TITLE
dependency on steal even when pluginified

### ISSUE THREAD

**Issue by dduponchel** [jupiterjs/jquerymx#37]
The file controller/view/view.js has a direct dependency on steal, even when pluginified.

Line 17 and 20 : 
`view = "//" + new steal.File('views/' + ...`

**Comment by jupiterjs** [comment]
controller/view should probably not be an available plugin.  It depends on steal and there isn't really a great way to avoid it.  Furthermore, it's tied to the JMVC folder struture, which steal is a big part of.

People should be using the jQuery modifiers if they are not using steal.
