### ISSUE TITLE
Error when generating model

### ISSUE THREAD

**Issue by BlessYAHU** [jupiterjs/jquerymx#4]
Getting the following on lates build: 
command: 
 js jquery/generate/model cookbook.models.client 
output: 
      cookbook/fixtures/clients.json.get 
there is nothing in steal/generate/templates/scaffold/model 
js: uncaught JavaScript runtime exception: TypeError: Cannot read 
property "leng 
th" from null 
running on windows.

**Comment by jupiterjs** [comment]
This is fixed.
