### ISSUE TITLE
model associations issue

### ISSUE THREAD

**Issue by amelon** [jupiterjs/jquerymx#43]
I'm trying to implement new "associations" method.

``` javascript
$.Model.extend("Contact",{
    attributes : { 
        birthday : 'date',
        tasks: "Task.models"
    },
...
```

I ran jquery/model/pages/associations.html exemple but there's an error

**this.model is not a function**
problem is here : res.push(this.model(raw[i])); in model.js row 924.

Actually, in "default" convert function, construct variable references a function using $.String.getObject.
when construct is called, "this" references Window object and not the wanted object.

I think getObject (jquery/lang) should return a function in that way

``` javascript
... (jquery/lang line 40)
                if( isContainer(current) ) {

                    ret = getNext(current, parts[i], add); 

                    if( ret !== undefined ) {

                        if ( add === false ) {
                            delete current[parts[i]];
                        }
                        //return ret; //current return
                                                //should return something like that
                        return function(val) {ret.call(current, val)}; 

                    }
...
```

I'm not sure of the closure side effect.

Maybe, the getObject function should return both object and function reference.

``` javascript
return [current, ret]
```

and let default converter manage the return value:

``` javascript
            "default" : function(val, error, type){
                var construct = $.String.getObject(type)
                return construct ? construct[1].call(construct[0], val) : val;
            }
```

**Comment by justinbmeyer** [comment]
yeah, this is fixed now.  Thanks for reporting!
