### ISSUE TITLE
documentjs.js", line 359: uncaught JavaScript runtime exception: TypeError: Cannot read property "name" from undefined

### ISSUE THREAD

**Issue by raspberryman** [jupiterjs/jquerymx#44]
The variable 'item' is not always defined when I run /documentjs/doc:

```
documentjs.js", line 359: uncaught JavaScript runtime exception: TypeError: Cannot read property "name" from undefined
```

I added a simple check to make sure it is defined, although there very well could be an underlying issue that is triggering this.
## More info...

When 'item' is undefined, the 'parent' parameter is an object with the following properties:
    name: jQuery.fn
    children: jQuery.fn.controllers,jQuery.fn.controller,jQuery.fn.closest,jQuery.fn.compare,jQuery.fn.curStyles,jQuery.fn.outerWidth,jQuery.fn.innerWidth,jQuery.fn.outerHeight,jQuery.fn.innerHeight,jQuery.fn.formParams,jQuery.fn.within,jQuery.fn.withinBox,jQuery.fn.models,jQuery.fn.model,jQuery.fn.jquery.model.services,jQuery.fn.prepend,jQuery.fn.append,jQuery.fn.after,jQuery.fn.before,jQuery.fn.text,jQuery.fn.html,jQuery.fn.replaceWith
     type: class
     parent: steal/dev/dev.js
     comment: 
     construct:   blah
## Patch:

``` javascript
diff --git a/documentjs.js b/documentjs.js
index 971c23a..b6ed60a 100644
--- a/documentjs.js
+++ b/documentjs.js
@@ -356,8 +356,8 @@ steal(  '//steal/generate/ejs',
        },
        // returns all recustive 'hard' children and one level of 'soft' children.
        listedChildren: function( item, stealSelf, parent ) {
-           var result = stealSelf ? [item.name] : [];
-           if ( item.children && !this.shallowParent(item, parent) ) {
+           var result = stealSelf && item ? item.name : [];
+           if ( item && item.children && !this.shallowParent(item, parent) ) {
                for ( var c = 0; c < item.children.length; c++ ) {
                    var child = docJS.objects[item.children[c]];
                    var adds = this.listedChildren(child, true, item);
```

**Comment by daffl** [comment]
Could you add a test for when this happens and file it as an issue in DocumentJS (https://github.com/jupiterjs/documentjs/issues)?

Thanks

**Comment by justinbmeyer** [comment]
yeah, it seems there is probably another problem and that not breaking here might be a mistake.

If we knew what was causing this, we could throw a warning.
