### ISSUE TITLE
Arguments passed to default events are lost

### ISSUE THREAD

**Issue by michaelchart** [jupiterjs/jquerymx#46]
When I trigger an event with some arguments:
$(element).trigger("someEvent", args)

"someEvent" : function(el, ev, args) { ... }
works fine and the function receives the arguments

however when the default event fires
"default.someEvent" : function(el, ev, args) { ... }
args is undefined

**Comment by moschel** [comment]
I fixed this here:

https://github.com/jupiterjs/jquerymx/commit/7c188296f3b51f1ca41c7bdc8d0e8a9c95b748cc

for your test here:

https://github.com/jupiterjs/jquerymx/commit/7806b327db38111ec67f1c00c92265ade8011c89
