### ISSUE TITLE
camelCased AppName

### ISSUE THREAD

**Issue by magikMaker** [jupiterjs/jquerymx#53]
If you generate an App with a camelcased name like MyApp using:
$> js jquery\generate\app MyApp

All files are placed in the folder 'myapp'

But if you then generate some models like this:
$>js jquery\generate\model MyApp.Models.MyModel

these are placed in the folder 'my_app' which actually makes alot more sense.

**Comment by lastzero** [comment]
I think the obvious solution is not to use camelCase in file/app names at all. But you are right: JMVC should convert the names always in the same way.

**Comment by magikMaker** [comment]
that's the "solution" I now used, but it would be nice if this was fixed.

**Comment by moschel** [comment]
Agreed, thanks for pointing this out.  I'll fix this soon while working on the new getting started guide.

**Comment by magikMaker** [comment]
Great, thanks.

**Comment by justinbmeyer** [comment]
Brian, any chance you fixed this?

**Comment by moschel** [comment]
fixed
