### ISSUE TITLE
$.View with tmpl engine returns undefined

### ISSUE THREAD

**Issue by jan--f** [jupiterjs/jquerymx#57]
hi,
i am having trouble with using the jquery tmpl engine via the $.View call. consider the following call:
`$.View("//test/views/test.tmpl",{heads:[{class: "h1", mes: "Ping"}, {class: "h2", mes: "Pong"}]})`

if test.tmpl look like this

```
{{each heads}}
    <h1>${mes}</h1>
{{/each}}
```

it returns correctly `<h1>Ping</h1>    <h1>Pong</h1>`

if test tmpl looks like this:

```
{{each heads}}
    <h1 class="${class}">${mes}</h1>
{{/each}}
```

undefined is returned whereas i would expect `<h1 class="h1">Ping</h1>    <h1 class="h2">Pong</h1>`

I just checked out the latest version of jquerymx and tested in Firefox 6.0

**Comment by polgfred** [comment]
Can you try a key other than `class`? `class` is technically a reserved word in JavaScript. 

-Fred 

--Science answers questions; philosophy questions answers.

**Comment by jan--f** [comment]
ups..yeah my mistake...you are right. stupid of me but some kind of error message would be nice if possible at all.
thanks
_edit_ 
it looks like it should be working regardless
https://developer.mozilla.org/en/JavaScript/Reference/reserved_words#Reserved_word_usage
not sure though if the issue is in tmpl or jquerymx
will test the same with bare $.tmpl

**Comment by jan--f** [comment]
yeah so it turns out jquery.tmpl has hickups with reserved words as IdentifierNames
`$.tmpl("{{each heads}}<h1 class='${class}'>${mes}</h1>{{/each}}",{heads:[{class: "h1", mes: "Ping"}, {class: "h2", mes: "Pong"}]})` produces an error, whereass `$.tmpl("{{each heads}}<h1 class='${foo}'>${mes}</h1>{{/each}}",{heads:[{foo: "h1", mes: "Ping"}, {foo: "h2", mes: "Pong"}]})` works fine

**Comment by polgfred** [comment]
It's not that simple. While it may be technically legal as a key in an object literal, when the template gets compiled, your reference to "class" will be a variable, which is not legal. Additionally, your mileage may vary from browser to browser. Best to just avoid them.

**Comment by jan--f** [comment]
yeah you are right...best avoid it.
Apparently it is possible though if `${$data["class"]}` is used...
http://api.jquery.com/jquery.tmpl/#comment-148052151

**Comment by polgfred** [comment]
Yes because in this case "class" is just a string, not an identifier. 

--Science answers questions; philosophy questions answers.
