### ISSUE TITLE
Strange redirects using $.route

### ISSUE THREAD

**Issue by p3k** [jupiterjs/jquerymx#58]
When I define e.g. `$.route('zone/:id', {id: 1})` and the corresponding event listener `$.route.bind('change', function() { /* ... */ })` I get strange redirects for certain routes:
- `#zone` is redirected to `#!zone/undefined&one=`
- `#!zone` is redirected to `#!zone/undefined&zone=`
- `#zone/1` is redirected to `#!zone/undefined&one%2F1=`
- `#!zone/1` is redirected to `#!zone/`
- `#!foobar` is redirected to `#!zone/undefined&foobar=`

`#!zone/2`, `#!zone/3` etc. work as expected.

**Comment by justinbmeyer** [comment]
This isn't a bug right now ... just maybe not what you expect.

Only routes like #! work.

#!zone/  should work for you, but it doesn't ignore the /.

I think the only problem is it not respecting #!zone, however you can do this like:

```
$.route('zone',{id: 1})
```

This might not be ideal.  You can re-open this as a feature request.
