### ISSUE TITLE
Wrong directory check when generating scaffold

### ISSUE THREAD

**Issue by xoa-zorn** [jupiterjs/jquerymx#6]
Here is the scenario:

Wanted namespace: CookBook 
This is just an example, i want that for namespacing my different Apps, like MyApp1, MyApp2.
I would prefer to use a real namespace, so Cook.Book (or My.App1, My.App2 ...) but that would place the apps in a subdirectory, what steal/the generators can't handle apparently.

The generator scripts will translate that to cook_book, which is ok for me.

So i execute: 
    js jquery\generate\app cook_book
      cook_book/cook_book.css
      cook_book/cook_book.html
      cook_book/cook_book.js
      cook_book/controllers
      ...
(a name translation here would be fine too, so that i can say app CookBook)

now i want to add a model:
    js jquery\generate\scaffold CookBook.Models.Recipe
      ! Error: folder cookbook/models does not exist!

it seems, that there a two different translations, one from app generation and the other from the model stuff ( app: CookBook -> coolbook, scaffold: CookBook -> cook_book) and the directory check uses the first.

if i create an empty directory cookbook/models and retry, it works.
    js jquery\generate\scaffold CookBook.Models.Recipe
      cook_book/controllers
      cook_book/controllers/recipe_controller.js
      cook_book/fixtures
      cook_book/fixtures/recipes.json.get
      ...

As described, the workaround is to create that empty directory, but this will clutter up the directory just more (btw: i don't like it, that everything has to be in one directory, multi-level namespacing would be really cool)

Am I'm doing something terribly wrong or how am I supposed to use the naming patterns?
Using cook-book looks really ugly (ex. in a Model: Cook-Book.Models.Recipe? cook-book.Models.Recipe?)

**Comment by jupiterjs** [comment]
The generators work with namespaces:

js jquery/generate/app  cook/book

js jquery\generate\scaffold Cook.Book.Models.Recipe

There's probably an issue with your example, but I'm not sure why you didn't think namespaces are working.

Also ... Cook-Book isn't valid JS.

**Comment by jupiterjs** [comment]
BTW, this is fixed in github ... do an update of jquerymx

**Comment by xoa-zorn** [comment]
Well, I can namespace (move to subdirectory), but if i want to relase my apps individually, everybody have to put them into that same subdirectory, even if somebody just uses one app.
On the other side, every plugin has to be in the root where steal is, because the paths are somewhat hardcoded in them, so i have to place them in the root. Or is there a way to override these paths in steal.plugins() so it change every path specified in the plugin? Maybe I'm missing something, played the whole day yesterday with it. The only real bug was this mentioned, which you fixed successfully.
To be honest i don't remember exactly, why I switched from Cook.Book to CookBook anymore :(
