### ISSUE TITLE
Controller plugin naming for 3.2

### ISSUE THREAD

**Issue by daffl** [jupiterjs/jquerymx#67]
Is the naming convention with removing _controllers_ from the name for the controller plugins still necessary for 3.2?
I saw that it was the cause of some confusion in the forums and with the plugin based application layout there won't be an official
controller folder anymore.

**Comment by justinbmeyer** [comment]
I like this idea.  The problem will be anyone updating from 3.1.  This is going to break things for them.

I'd like to hold off until 3.3.  So, lets make this change in a few weeks after 3.2 comes out.
