### ISSUE TITLE
3.2 beta 2: defaluts do not inherit in inherited controllers

### ISSUE THREAD

**Issue by wclr** [jupiterjs/jquerymx#69]
It seems that  defaluts do not inherit in inherited controllers in beta 2 of 3.2

$Controller.extend("Parent",
{
 defaults: {some_option:"default_value"}
}
{

})

Parent.extend("Child",
{

}
{
  init: function(){
    //this.options.some_option == undefined
  }
}).;

**Comment by justinbmeyer** [comment]
this has been fixed in #68

**Comment by wclr** [comment]
ok, didn't notice. And will a beta version with this fix be avaliable, or it will be only in final release?
