### ISSUE TITLE
Compressor fails while building views (.ejs) due to white space in HTML

### ISSUE THREAD

**Issue by damir8** [jupiterjs/jquerymx#72]
When building the production version of an app, the compressor fails if there is any white space ("\n", "\t", etc) inside the .ejs templates:

/_-----------------------------------------------_/

> #### jquery/lang/string/rsplit/rsplit.js
> #### appname/list/views/init.ejs
> #### appname/list/views/template.ejs
> #### ])));___v1ew.push(">
> #### ");___v1ew.push((jQ
> #### timer error
> #### function () {
> #### _this.onreadystatechange();
> #### }
> #### TypeError: Cannot find function error in object Type: string, value: >, from: 435930, to: 435932.

/_-----------------------------------------------_/

// THIS WORKS:

``` html
<%for(var i = 0; i < this.length ; i++){%><li <%= this[i]%>><%== $.View('//appname/list/views/template.ejs', this[i] )%></li><%}%>
```

// THIS DOES NOT WORK:

``` html
<%for(var i = 0; i < this.length ; i++){%>
    <li <%= this[i]%>>
        <%== $.View('//appname/list/views/template.ejs', this[i] )%>
    </li>
<%}%>
```

**Comment by moschel** [comment]
Pretty sure this is fixed now.  Thanks for reporting it.

**Comment by damir8** [comment]
That was quick. Tested and it works.

Thanks!
