### ISSUE TITLE
isNew() on model treats blank ids as if an id exists and sends .save() calls to update()

### ISSUE THREAD

**Issue by uTestMichaelL** [jupiterjs/jquerymx#86]
Since formParams() returns {id: ""} from a form with a field <input type="hidden" name="id" />
this breaks the formParams() and isNew() integration.

From Justin on: http://forum.javascriptmvc.com/topic/isnew-on-model-treats-blank-ids-as-if-an-id-exists-and-sends-save-calls-to-update

"Those two are made for each other.  We can probably change it to ignore an empty string too. "

**Comment by daffl** [comment]
It does ignore empty strings when using

```
$(form).form_params(true)
```

This converts strings that look like numbers and booleans and empty strings will be ignored.
Maybe we should default it to true?

**Comment by daffl** [comment]
I also updated the isNew check in $.Model. An empty string as a model id can't be used anyway.
