### ISSUE TITLE
Steal.production loads template instead of cached view

### ISSUE THREAD

**Issue by Luwe** [jupiterjs/jquerymx#9]
Largely based on this issue: http://code.google.com/p/javascriptmvc/issues/detail?id=91

A few snippets to clarify:

yourapp.js:

<pre><code>steal.plugins(
  'jquery/controller',
  'jquery/controller/view',     
  'jquery/view/ejs')

  .views('init.ejs')</code></pre>

Loads init.ejs in the views folder into the production file of your app. An absolute path isn't given, because steal adds the absolute path itself. I've tried adding the absolute path as well, but it still gives the same problems. When using the view as follows in a controller:

some_controller.js:

<pre><code>$('div').append(this.view('//absolute/path/to/views/init'));</code></pre>

or

<pre><code>$('div').append('//absolute/path/to/views/init', {});</code></pre>

It succesfully loads the view in development mode. The view also gets added to the production build, as seen in the final production build:

production.js:

<pre><code>$.View.preload('absolute_path_to_views_init_ejs',jQuery.EJS(function(_CONTEXT,_VIEW) { try { with(_VIEW) { with (_CONTEXT) {var ___v1ew = [];___v1ew.push("&lt;div id=\"somebox\" class=\"someblock\">\n");
___v1ew.push("&lt;/div>");; return ___v1ew.join('');}}}catch(e){e.lineNumber=null;throw e;} }));;</code></pre>

But somehow, the production build is still looking for init.ejs in the views folder. It isn't loading the cached view in production.js. I've also checked if $.View.cache was set to true and this seems to be the case.

**Comment by jupiterjs** [comment]
Is the code that's using the view running after the view has been loaded?

**Comment by Luwe** [comment]
Hmm yes, that seemed to be the problem. Loading the views before the controller fixed it. I didn't know that needed to happen. Only thought that steal needed to know what to load in production mode.

**Comment by jupiterjs** [comment]
Well, order matters.  Steal basically packages up things in the order you steal them.  If you're trying to use a resource before it has been loaded, steal will break.  

This is tricky because in development mode, steal just loads the views when it's time to load them, so you can't actually tell that in production, the views are being 'preloaded' after you are trying to use them.

Btw, I did the following and it works:

.views('init.ejs').then(function(){
        $('h1').html("//foo/views/init.ejs",{})
    })
