### ISSUE TITLE
View from an inline template does not support hyphenated types

### ISSUE THREAD

**Issue by jeffrose** [jupiterjs/jquerymx#93]
Retrieving a View from an inline template fails if that the script tag has a hyphen in the type.

``` html
<script type="text/x-template" id="my-view">
...
</script>
<script type="text/javascript">
var view = $.View('my-view', { ... });
</script>
```

Currently [jsrender](https://github.com/BorisMoore/jsrender), the replacement for jQuery Tmpl, is using a type of `text/x-jquery-tmpl` for its templates, though that is likely to change to something like `text/x-jsrender` prior to the release.

The error seems to occur with this line in **jquery.view.js**:

``` javascript
suffix = el.type.match(/\/[\d\w]+$/)[0].replace(/^\//, '.');
```

Apparently the regular expression doesn't like the hyphen.
A simple fix would be:

``` javascript
suffix = el.type.replace('x-', '').match(/\/[\d\w]+$/)[0].replace(/^\//, '.');
```

While at the end of the day, no one is forcing a developer to prepend a **x-** on their template script types, it is the standard way of denoting a MIME type extension, i.e. a MIME type that is not registered with IANA, so it seems like it should be supported.

**Comment by justinbmeyer** [comment]
seams reasonable.  But I would only replace the x- at the start of the type.  And support - if people want it after that.

**Comment by jeffrose** [comment]
Even though it was in my example, I had actually missed the fact that the regular expression still needs to be changed to accept hyphens even if the preceding `x-` is removed (too much coffee, not enough sleep).

So that would mean something like:

``` javascript
suffix = el.type.replace(/^x\-/, '').match(/\/[\d\w\-]+$/)[0].replace(/^\//, '.');
```

**Comment by justinbmeyer** [comment]
I'm working on this now,  but just for anyone else finding this, it's a best practice to use steal to load your scripts.  It's much faster.
