### ISSUE TITLE
bug in fixtures with two position value for wildcard in templated url

### ISSUE THREAD

**Issue by joris77** [jupiterjs/jquerymx#97]
I have this fixture:

$.fixture("POST /days/{dayId}/time_slots.json", function(original, settings, headers) {
         alert(days[original.data.dayId].date)
    })

when the url posted is: /days/17/time_slots.json or /days/27/time_slots.json

original.data.dayId evaluates to 7

I can trace it back to the fixture.js  line 430. In the _getData function over there the res variable also displays 7 as the result. 

Javascriptmvc version: 3.2
Browser: Firefox

**Comment by justinbmeyer** [comment]
Fixed here:

https://github.com/jupiterjs/jquerymx/commit/0fe78d7735f45a2added4a82d82ce4f3bc2893d1#dom/fixture/fixture.js
